version: "3"

services:
  api:
    container_name: style-bert-vits2-api
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - UID
        - GID
        - UNAME=user
        - GNAME=user
    ports:
      - "5000:5000"
    volumes:
    - ./bert:/home/user/app/bert
    - ./slm:/home/user/app/slm
    - ./pretrained:/home/user/app/pretrained
    - ./pretrained_jp_extra:/home/user/app/pretrained_jp_extra
    - ./model_assets:/home/user/app/model_assets
