version: "3"

services:
  api:
    container_name: style-bert-vits2-api
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - UID
        - GID
        - UNAME=user
        - GNAME=user
    ports:
      - "5000:5000"
    volumes:
    - data:/home/user/app/bert
    - data:/home/user/app/slm
    - data:/home/user/app/pretrained
    - data:/home/user/app/pretrained_jp_extra
    - data:/home/user/app/model_assets
volumes:
  data:
